import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

export const generateInterviewPDF = (session, candidateName, outputPath) => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 40 });
    const stream = fs.createWriteStream(outputPath);

    doc.pipe(stream);

    /* ===== LOGO (TOP RIGHT) ===== */
    const logoPath = path.join(process.cwd(), 'assets', 'college-logo.png');
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, 460, 20, { width: 80 });
    }

    /* ===== HEADER ===== */
    doc
      .fontSize(10)
      .text(`Interview ID: ${session._id}`, 40, 30, { align: 'left' });

    doc.fontSize(18).text('AI Interview Result', { align: 'center' });
    doc.moveDown(2);

    /* ===== SCORE CALCULATION ===== */
    const maxScore = session.questions.length * 10;
    const percentage = ((session.totalScore / maxScore) * 100).toFixed(2);

    let grade = 'D';
    if (percentage >= 80) grade = 'A';
    else if (percentage >= 60) grade = 'B';
    else if (percentage >= 40) grade = 'C';

    /* ===== CANDIDATE INFO ===== */
    doc.fontSize(12).text(`Candidate Name: ${candidateName}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.text(`Total Score: ${session.totalScore} / ${maxScore}`);
    doc.text(`Percentage: ${percentage}%`);
    doc.text(`Grade: ${grade}`);
    doc.moveDown();

    /* ===== TABLE HEADER ===== */
    const colX = {
      qno: 40,
      question: 80,
      answer: 270,
      score: 500,
    };

    let y = doc.y;

    doc.fontSize(11).text('Q.No', colX.qno, y);
    doc.text('Question', colX.question, y);
    doc.text('Answer', colX.answer, y);
    doc.text('Score', colX.score, y);

    doc
      .moveTo(40, y + 15)
      .lineTo(560, y + 15)
      .stroke();
    y += 25;

    /* ===== TABLE ROWS ===== */
    session.answers.forEach((item, index) => {
      if (y > 700) {
        doc.addPage();
        y = 50;
      }

      doc.fontSize(10).text(index + 1, colX.qno, y);
      doc.text(item.question, colX.question, y, { width: 170 });
      doc.text(item.answer, colX.answer, y, { width: 210 });
      doc.text(`${item.score}/10`, colX.score, y);

      y += 60;
    });

    /* ===== OVERALL FEEDBACK (LAST PAGE) ===== */
    doc.addPage();

    let overallFeedback = 'Needs improvement.';
    if (percentage >= 80) {
      overallFeedback =
        'Excellent performance with strong understanding of core concepts.';
    } else if (percentage >= 60) {
      overallFeedback = 'Good performance with minor areas for improvement.';
    } else if (percentage >= 40) {
      overallFeedback =
        'Average performance. Focus on strengthening fundamentals.';
    }

    doc.moveDown(4);
    doc.fontSize(14).text('Overall Feedback', { underline: true });
    doc.moveDown(1);
    doc.fontSize(12).text(overallFeedback);

    /* ===== FOOTER (ALL PAGES) ===== */
    const addFooter = () => {
      doc
        .fontSize(9)
        .text(
          'Generated by AI Interview System | Your College Name',
          40,
          doc.page.height - 40,
          { align: 'center' }
        );
    };

    addFooter();
    doc.on('pageAdded', addFooter);

    doc.end();

    stream.on('finish', resolve);
  });
};
